<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1.cs" />
    <Compile Remove="Form1.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Form1.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NTier.Business\NTier.Business.csproj" />
    <ProjectReference Include="..\NTier.DataAccess\NTier.DataAccess.csproj" />
    <ProjectReference Include="..\NTier.Entities\NTier.Entities.csproj" />
  </ItemGroup>

</Project>